# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install apt update
        run: sudo apt update

      # Runs a set of commands using the runners shell
      - name: Install python3
        run: |
          sudo apt install ansible python3-pip -y

      - name: Install python modules
        run: pip3 install -r requirements.txt

      - name: Python version modules
        run: python3 -V

      - name: pip version modules
        run: pip3 -V

      - name: pip list modules
        run: pip3 list
      
      - name: Extract data from mariadb
        run: python3 pythonmariadb.py
        env:
          databasename: ${{ secrets.DATABASENAME }}
          databasehost: ${{ secrets.DATABASEHOST }}
          databaseusername: ${{ secrets.DATABASEUSERNAME }}
          databasepassword: ${{ secrets.DATABASEPASSWORD }}
          databaseport: ${{ secrets.DATABASEPORT }}

      - name: print test.csv
        run: cat test.csv

      - name: Email job completion
        run: python3 sendingmail.py
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          SMTP_ADDRESS: ${{ secrets.SMTP_ADDRESS }}